### ISSUE TITLE
Including image in the email

### ISSUE THREAD

**Issue by psychok7** [BradWhittington/django-templated-email#48]
Hey there guys, how can i include an image in my Html email template??

i tried : `<p><img src="{{site_domain}}/static/images/logo_email.jpg" alt="" height="109" width="65"></p>` with no luck

**Comment by paulnurkkala** [comment]
What URL does that template script generate when the email is sent? Is it properly set? Is that image publically viewable when you're not logged in/on a different domain? 

Keep in mind that the email is no longer a part of the domain when it's sent off, so you have to make sure that the image can be viewed remotely. My suggestion would be to create a static site or subdomain and host that image there, then give the ABSOLUTE link to that image. 

If you DO need the image to populate dynamically, then you're going to need to do other trickery.

**Comment by psychok7** [comment]
@paulnurkkala thanks, the problem was that the image was not publically viewable. silly me
