### ISSUE TITLE
AWS SES SERVICE INTEGRATION

### ISSUE THREAD

**Issue by armsmani** [BradWhittington/django-templated-email#52]
Hi Team,

Is it possible to incorporate AWS SES in django-templated-email.

Note:
I already tried above scenario but i got below errors:
SAXParseException at /url
<unknown>:1:0: syntax error

**Comment by BradWhittington** [comment]
Hi, this is outside the scope the project, the project uses Django's built in abstractions for mailer (have a look at django-ses for SES integration).
